//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KutuphaneYonetimSistemi.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Kitap_Talep
    {
        public int ID { get; set; }
        public string Kitap_Ad { get; set; }
        public string Yazar_Ad { get; set; }
        public string Kategori_Ad { get; set; }
        public Nullable<System.DateTime> İstenilme_Tarihi { get; set; }
        public Nullable<bool> Temin_Edildi { get; set; }
        public Nullable<bool> Bekleniyor { get; set; }
    }
}
