//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KutuphaneYonetimSistemi.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_FaturaKalem
    {
        public int ID { get; set; }
        public Nullable<int> Fatura_ID { get; set; }
        public Nullable<int> Kitap_ID { get; set; }
        public Nullable<int> Kategori_ID { get; set; }
        public Nullable<int> Yazar_ID { get; set; }
    }
}
