//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KutuphaneYonetimSistemi.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLAction
    {
        public int ActionID { get; set; }
        public Nullable<int> ActionBook { get; set; }
        public Nullable<int> ActionUser { get; set; }
        public Nullable<int> ActionWorker { get; set; }
        public Nullable<System.DateTime> ActionBeginningDate { get; set; }
        public Nullable<System.DateTime> ActionFinishDate { get; set; }
        public Nullable<int> LibraryID { get; set; }
        public Nullable<bool> ActionCase { get; set; }
        public Nullable<System.DateTime> userLendingTime { get; set; }
    }
}
