//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KutuphaneYonetimSistemi.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLFatura
    {
        public int ID { get; set; }
        public Nullable<int> Uye_ID { get; set; }
        public Nullable<System.DateTime> Aldığı_Tarih { get; set; }
        public Nullable<System.DateTime> Teslim_Tarihi { get; set; }
        public Nullable<bool> Aldı { get; set; }
        public Nullable<bool> Verdi { get; set; }
        public string Tel { get; set; }
        public string Adress { get; set; }
        public Nullable<int> LIBRARYID { get; set; }
    }
}
